### ISSUE TITLE
No such file or directory: 'session/data/clean/data.json'

### ISSUE THREAD

**Issue by alphafox02** [konicst1/lorattack#1]
Testing on 
22.04
Python 3.10 w/ venv

On a clean install, when trying to start the GUI, it complains there's no directory and/or data.json. I've taken a look at the session python file and it would appear it should create a new directory and file, but that does not appear to happen and so far the GUI is unable to load. I'll continue to troubleshoot in case it's just an issue on my end. 

```
Traceback (most recent call last):
  File "/home/dragon/WarDragon/lorattack/main.py", line 10, in <module>
    main()
  File "/home/dragon/WarDragon/lorattack/main.py", line 6, in main
    guimanager = GUIManager()
  File "/home/dragon/WarDragon/lorattack/src/gui_manager.py", line 141, in __init__
    self.session_manager.list_pcap_files()
  File "/home/dragon/WarDragon/lorattack/src/session_manager.py", line 194, in list_pcap_files
    _, session_data = self.load_current_session()
  File "/home/dragon/WarDragon/lorattack/src/session_manager.py", line 86, in load_current_session
    with open(os.path.join(session_dir, 'data.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'session/data/clean/data.json'
```

**Comment by alphafox02** [comment]
I manually made the clean directory along with the data.json containing the following. 

{
    "AppKey": null,
    "NwkKey": null,
    "JoinRequest_DevEUI": null,
    "JoinRequest_AppEUI": null,
    "JoinRequest_JoinEUI": null,
    "JoinRequest_DevNonce": null,
    "JoinAccept_AppNonce": null,
    "JoinAccept_JoinNonce": null,
    "JoinAccept_NetID": null,
    "JoinAccept_DevAddr": null,
    "AppSKey": null,
    "NwkSKey": null,
    "NwkSEncKey": null,
    "SNwkSIntKey": null,
    "FNwkSIntKey": null
}

Gui loads.

**Comment by konicst1** [comment]
Hi there, 
thanks for noting that. I have added plain session data to prevent this. I still work on this project, so let me know if you encounter any trouble.
Cheers

**Comment by alphafox02** [comment]
Completely unrelated to this issue, but I am trying to understand where the decoding of packets to pcap would be happening? 

I’ve looked at the sniffer python file and the grc files and can’t find any sign of the tool writing to pcap when/if there’s detection. 

I notice in the grc flow graphs there’s a network message endpoint, but I’m not seeing where that’s connected to or used. Is there something I’m missing?

**Comment by alphafox02** [comment]
I see now, I wasn’t looking closely enough 

https://github.com/konicst1/lorattack/blob/master/src/analyzer.py

I’ll open another ticket as needed if I run into anything else.
